plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: james
description: messybarn studios website
lang: en
locale: en_GB
url: "https://messybarn.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20